### ISSUE TITLE
Same field name on multiple children tables

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/metaproject#2]
Multiple children table with the same field should allow to remap the field name on the generated view.

Example:

 * od_wastewater_structure
   * od_manhole
   * od_special_structure

Both child tables have a field `function`

Either the field should automatically be renamed on the view to `manhole_function` and `special_structure_function` or it should accept a remap name like

```
{
  "od_wastewater_structure": {
    "pkey_nextval": " qgep.generate_oid(''od_wastewater_structure'')", 
    "inherited_by": {
      "od_special_structure": {
        "table_name": "qgep.od_special_structure", 
        "pkey": "obj_id",
        "fields": {
           "function": {
             "remap": "special_structure_function"
          }
        }
      }, 
      "od_manhole": {
        "table_name": "qgep.od_manhole", 
        "pkey": "obj_id",
        "fields": {
           "function": {
             "remap": "manhole_function"
          }
        }
      }
    }, 
    "pkey": "obj_id"
  }
}
```

**Comment by m-kuhn** [comment]
If not remapped, I think it should just be merged and NULL'ed if not present in the subtable.

E.g.

**Comment by 3nids** [comment]
What if not null but different ?
Concatenate ? Specify a master column ?
How do you handle on update ?

**Comment by m-kuhn** [comment]
I am not sure I understand your question.
An object is always just of one type (one subclass) so there is no conflicting information.

So there are two possibilities on the merged view, should there be

 * one merged field for the subclass fields (if they are semantically the same)
 * one field for each subclass field (if they are semantically not the same)

Example 1: Merge
========

**Depth** is portable between the different subclasses. Hence it shall be treated as one single field on the parent table which is NULL for wastewater structure types which do not support it.

Input
------

**Wastewater Structure**

| obj_id |
|--------|
| MH1    |
| SS1    |

**Manhole**

| obj_id | depth |
|--------|-------|
| MH1    | 15    |

**Special Structure**

| obj_id | depth |
|--------|-------|
| SS1    | 20    |

Wastewater Structure View (Result)
-------------------

| obj_id | depth |
|--------|-------|
| MH1    | 15    |
| SS1    | 20    |

Example 2: Remap
========

**Function** is different on manhole and special structure. The foreign key defined on the two subtables point to different value lists. Therefore the values are not portable and cannot be mapped to one merged field on the view.

Input
-----

**Wastewater Structure**

| obj_id |
|--------|
| MH1    |
| SS1    |

**Manhole**

| obj_id | function |
|--------|-------|
| MH1    | 1004    |

**Special Structure**

| obj_id | function |
|--------|-------|
| SS1    | 2008    |

Wastewater Structure View (Result)
-------------------


| obj_id | manhole_function | special_structure_function |
|--------|------------------|----------------------------|
| MH1    | 1004             | NULL                       |
| SS1    | NULL             | 2008                       |

**Comment by 3nids** [comment]
Got it, thanks for the detailed clarification
